from cashier import Transaction

customer_1 = Transaction()
customer_1.add_item({ 'Ayam Goreng': [2, 20000], 'Pasta Gigi': [3, 15_000] })
customer_1.update_item_name('Ayam Gorengx', 'Ayam goreng 2')
customer_1.update_item_name('Ayam Goreng', 'Ayam goreng 2')
customer_1.update_item_price('Ayam Goreng 2', 'Ayam goreng 2')
customer_1.update_item_price('Ayam Goreng', 30000)
customer_1.update_item_price('Ayam goreng 2', 30000)
customer_1.update_item_qty('Ayam Goreng 2', 'Ayam goreng 2')
customer_1.update_item_qty('Ayam Goreng', 5)
customer_1.update_item_qty('Ayam goreng 2', 10)
customer_1.delete_item('Ayam Goreng')
customer_1.delete_item('Pasta Gigi')
customer_1.reset_transaction()
customer_1.check_order()
customer_1.add_item({ 'Ayam Goreng': [8, 20000], 'Pasta Gigi': [8, 15_000] })
customer_1.check_order()
customer_1.total_price()